### ISSUE TITLE
鉴权参数解析异常

### ISSUE THREAD

**Issue by xingyongqiang** [gaowei-space/meituan-pub-union#4]
SearchDealsRequest 提示鉴权参数解析异常,CategoriesRequest都是正常的,大佬遇到过没有

**Comment by gaowei-space** [comment]
确实，应该是美团接口有调整了，我找时间看看，你这边业务中用到了？如果着急可以自己先看看文档，调整下逻辑

**Comment by xingyongqiang** [comment]
我看参数好像是什么变化

**Comment by gaowei-space** [comment]
确认了一下，美团对到店API做了调整，如图：
<img width="1170" alt="image" src="https://user-images.githubusercontent.com/10205742/170806171-c4aa4d52-fc77-4e48-a742-4dd863874b53.png">

**Comment by xingyongqiang** [comment]
明白,多谢,等于说现在他们连商品搜索这个也调整了
