### ISSUE TITLE
在SearchDealsRequest中utmMedium参数问题 ？

### ISSUE THREAD

**Issue by zio-zhang** [gaowei-space/meituan-pub-union#5]
使用美团接口，查询商品时，有一个utmMedium参数，不是太理解，
 
 `
utmMedium | String | 必须 |
二级渠道（AES加密），该参数用于二级分销场景跟单返佣，一级分销场景下传入一个默认值(例：10000并加密)即可 `
`
传入值是要aes加密，这个值不太清楚从那里获取，一直没找到这个值，导致接口一直调用不功能，望参提点一下

**Comment by liaoshengping** [comment]
@zio-zhang   是的，这个需要在外层加密一下

**Comment by zio-zhang** [comment]
@liaoshengping  加密我清楚，我是想了解一下，这个参数在那可以获取到，一直没找到这个参数，卡住了，特咨询一下大佬

**Comment by liaoshengping** [comment]
@zio-zhang  这个参数是你自定义的标识，下单成功后你可以获取到该数据

**Comment by zio-zhang** [comment]
@liaoshengping 

```
$app_key    = '****';
$utm_source = '***';

function _encrypt($data,$app_key): string
{
    $str = openssl_encrypt($data, 'AES-128-ECB', $app_key);
    return bin2hex(base64_decode($str));
}

// 实例客户端类
$client = new Client($app_key, $utm_source);
$request= new SearchDealsRequest();
$request->setPlatformId(1);
$request->setCat0Id(50);
$request->setUtmSource($utm_source);
$request->setUtmMedium(_encrypt('10000',$app_key));
$response = $client->syncInvoke($request);
print_r($response->getContent());
```
打印的结果为
```
Array
(
    [code] => 501
    [msg] => 鉴权参数解析异常
    [serverTrackId] => 4315059692754464912
)
```
查询省，市及类别接口，可以正常获取数据

**Comment by liaoshengping** [comment]
这个是美团限制 了商户这个功能，需要向美团申请才可以用了 @zio-zhang

**Comment by liaoshengping** [comment]
首页微信，发资料给你

**Comment by zio-zhang** [comment]
谢谢，但首页没找到微信，我的微信zhihorse

**Comment by zio-zhang** [comment]
@liaoshengping  测试用的帐号，已签约，应该有权限了，是还要申请什么功能吗？

**Comment by zio-zhang** [comment]
@liaoshengping 能发份资料给我不，不清楚错在那了，
zio.zhang@foxmail.com 十分感谢

**Comment by gaowei-space** [comment]
正如 @liaoshengping  所说，`utmMedium` 该值为自定义的标识，用于确认CPS订单来源于哪。`utmMedium` 通常可以设置为用户id。 @zio-zhang

**Comment by zio-zhang** [comment]
@gaowei-space， 这个清楚了，主要还是，utmMedium有值，接口返回还是> 鉴权参数解析异常。已签约，有权限，不清楚问题 在那。有一个示例就好一点

**Comment by gaowei-space** [comment]
@zio-zhang   接口是指这个 `SearchDealsRequest` 么？ 如果是的话，该接口已经停止访问了[[详情](https://github.com/gaowei-space/meituan-pub-union/issues/4)]； 如果是其他接口，可以查看[美团官网](https://pub.meituan.com/#/entry)公告确认

**Comment by zio-zhang** [comment]
https://union.dianping.com/api/search/deals
这个接口，我都是先看官方文档 ，再搜到这个开源的
@gaowei-space

**Comment by liaoshengping** [comment]
@zio-zhang  你要向美团申请这个接口
`如需申请保留API功能，可以在后台发邮件申请不取消。（发送至：MTFX@meituan.com）邮件内容：渠道名称，渠道ID，说明资源情况（未来期望订单量较高，具体是什么位置，用户量有多大等等）后续会有预估订单量多少等等~`

**Comment by zio-zhang** [comment]
好的，谢谢
